"""
Django settings for {PROJECT} project.

Generated by 'django-admin startproject' using Django {DJANGO_VERSION}.

For more information on this file, see
https://docs.djangoproject.com/en/{LINK_VERSION}/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/{LINK_VERSION}/ref/settings/
"""

SETTINGS_IMPORT
from dj_database_url import parse as dburl
from decouple import Csv, config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
SETTINGS_BASE_DIR


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/{LINK_VERSION}/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default=[], cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # thirty apps
    'django_extensions',
    # my apps
    '{PROJECT}.accounts',
    '{PROJECT}.core',
    '{PROJECT}.crm',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '{PROJECT}.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '{PROJECT}.wsgi.application'


# Database
# https://docs.djangoproject.com/en/{LINK_VERSION}/ref/settings/#databases
